name: Docker

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker builds
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Rails - Image metadata
        id: rails_meta
        uses: docker/metadata-action@v3
        with:
          images: wafflehacks/hackathon-manager
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Rails - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.rails_meta.outputs.tags }}
          labels: ${{ steps.rails_meta.outputs.labels }}
          target: rails
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,src=/tmp/.buildx-cache-new

      - name: Sidekiq - Image metadata
        id: sidekiq_meta
        uses: docker/metadata-action@v3
        with:
          images: wafflehacks/hackathon-manager-sidekiq
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Sidekiq - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.sidekiq_meta.outputs.tags }}
          labels: ${{ steps.sidekiq_meta.outputs.labels }}
          target: sidekiq
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,src=/tmp/.buildx-cache-new

      # Temp fix for:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move build cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
